Update google-cloudrun-docker.yml

diff --git a/.github/workflows/google-cloudrun-docker.yml b/.github/workflows/google-cloudrun-docker.yml
--- a/.github/workflows/google-cloudrun-docker.yml
+++ b/.github/workflows/google-cloudrun-docker.yml
@@ -43,38 +43,53 @@
 #   Artifact Registry IAM permissions         - https://cloud.google.com/artifact-registry/docs/access-control#roles
 #   Container Registry vs Artifact Registry   - https://cloud.google.com/blog/products/application-development/understanding-artifact-registry-vs-container-registry
 #   Principle of least privilege              - https://cloud.google.com/blog/products/identity-security/dont-get-pwned-practicing-the-principle-of-least-privilege
----
+#---
 name: Build and Push Python Image to Google Cloud Platform
+
 on:
   push:
-    branches: [ main ]
+    branches:
+      - main
+
 jobs:
   build-push-gcr:
     name: Build and Push to GCP
     runs-on: ubuntu-latest
+
     env:
       IMAGE_NAME: apieduconline
       PROJECT_ID: astral-option-412114
+
     steps:
     - name: Checkout
       uses: actions/checkout@v2
 
-    - uses: 'google-github-actions/setup-gcloud@v2'
+    - name: Set up Google Cloud SDK
+      uses: google-github-actions/setup-gcloud@v2
       with:
         service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
         project_id: ${{ env.PROJECT_ID }}
         export_default_credentials: true
 
     - name: Build Docker Image
-      run: docker build -t $IMAGE_NAME:latest .
+      run: |
+        docker build -t $IMAGE_NAME:latest .
+        if [ $? -ne 0 ]; then
+          echo "Failed to build Docker image. Exiting..."
+          exit 1
+        fi
 
     - name: Configure Docker Client
-      run: |-
-        gcloud auth configure-docker --quiet
-        gcloud auth configure-docker europe-west9-docker.pkg.dev --quiet
+      run: gcloud auth configure-docker --quiet
 
     - name: Push Docker Image to Container Registry (GCR)
-      run: docker push $IMAGE_NAME:latest
+      run: |
+        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest
+        if [ $? -ne 0 ]; then
+          echo "Failed to push Docker image to GCR. Exiting..."
+          exit 1
+        fi
+
 
     # - name: Push Docker Image to Artifact Registry
      # env:
